### ISSUE TITLE
Best way to use E2E tests now

### ISSUE THREAD

**Issue by dimitar-ivanov-tryzens** [SnowdogApps/magento2-alpaca-theme#151]
Hi, thanks for the great work. I can see that Cypress E2E tests have reasonable coverage in the open PR, and are a good base. Unfortunately, all data-testid attributes are available only on develop branch. Do you plan to release those or some easy way to get only data-testid related commits and merge them in a custom theme?

**Comment by Igloczek** [comment]
You need to wait, it's work in progress, we will release it when it will be ready to use, until then you can use `develop`, if you are brave enough :)
We are not planning to release data-testids as some kind of patch or standalone thing, since custom themes, are custom, because are customized, so it will generate a lot of mess when you try to apply it, you will have to do it manually for stuff you overwrite.
