### ISSUE TITLE
snownav.php - 404 not found

### ISSUE THREAD

**Issue by dfigliolia** [SnowdogApps/magento2-alpaca-theme#172]
I have this error in console:
Failed to load resource: the server responded with a status of 404 () " /snownav.php"

How can I solve it?
Where can I find it?

**Comment by Januszpl** [comment]
@dfigliolia 

Can you provide more details? 
Which server? Local? production? Nginx, apache?

Probably what you are missing is to add configuration to your servers so it can find /snownav.php in /pub/snownav.php

**Comment by gfigliolia** [comment]
It is a production server, Apache + Nginx as proxy. Can you please tell me the purpose of the snownav.php file? Because It seems that everything is working properly and I can't find it in pub/ folder.

Thanks

**Comment by dfigliolia** [comment]
It is a production server, Apache + Nginx as proxy. Can you please tell me the purpose of the snownav.php file? Because It seems that everything is working properly and I can't find it in pub/ folder.

Thanks

**Comment by Igloczek** [comment]
@Januszpl we need to provide some fallback mechanism in the template for non Solr users, since we are not planning to open source this code.

@dfigliolia please change this line:
https://github.com/SnowdogApps/magento2-alpaca-theme/blob/8851fbd9f169f1d155b11c456ed1ffc3854e551b/Magento_Theme/templates/header/search.phtml#L22

to this:
https://github.com/magento/magento2/blob/7404d9d754e03c813fad91c7a551006b66d827e1/app/code/Magento/Search/view/frontend/templates/form.mini.phtml#L27

and you will good to go.
