### ISSUE TITLE
location of child theme, and path defined in themes.json

### ISSUE THREAD

**Issue by kennylawrence** [SnowdogApps/magento2-alpaca-theme#174]
Hello - there was a reply to an issue in the Snowdog Blank SASS theme git repo which suggested that a child theme for a magento installation using frontools should go into /vendor/{client}/{client-theme}. However, when doing that, Magento wasn't able to find my theme in the admin panel. I moved it to /app/design/frontend/{client}/{client-theme}, and that worked.

Running "gulp styles && gulp babel && gulp svg" doesn't throw any errors, but I'm not sure if it's really accessing the correct location for my child theme.

Before I go forward I just want to make sure that my /dev/tools/frontend/config/themes.json is correct for the child theme's "src" variable. Should it reference vendor/ or should it reference app/design/frontend/ ? As you know, the README for this project defines the default themes.json for a child theme with alpaca as parent such that "src" for the child references vendor/  - which didn't let Magento find it.

eg,

    "src": "vendor/{vendor-name}/theme-frontend-{theme-name}",

or

    "src": "app/design/frontend/{vendor-name}/theme-frontend-{theme-name}",

Did something change in Magento that caused it to stop loading themes in the vendor/ folder? or have I mis-configured some other file?

**Comment by Igloczek** [comment]
You are in the wrong repository, it's Alpaca, not Blank. Also you problem is not related to any theme and it's not at issue related to the code. You should ask such a questions on [StackOverflow](https://magento.stackexchange.com/) or [Slack](https://github.com/magento/magento2/wiki/Slack-Channels).

`vendor` based paths are for Composer install, which probably you are not using, that's why you had to put that in `app` to work correctly.

The `src` in `themes.json` should point to the real place where you have code, so `app` based path.
